version: "3"
services:
  app:
    image: node:18.18.2-slim
    environment:
      - SAMPLE_USER=user
      - TZ=Asia/Tokyo
      - DEBIAN_FRONTEND=noninteractive
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ./src/:/app/
    entrypoint: /bin/bash
    command: -c "tail -f /dev/null"
